#!/usr/bin/env bash

BLUE="\033[0;34m"
CYAN="\033[0;36m"
PURPLE="\033[0;35m"
NO_COLOR="\033[0m"

set -euo pipefail

function run() {
  INSTALL_PATH=/var/lib
  AV_PATH=$INSTALL_PATH/aviary/av
  GIT_URL=https://github.com/team-video/aviary.sh.git
  INVENTORY_GIT_URL="https://github.com/P5vc/ServerConfigurations.git"
  CONFIG_FILE=${INSTALL_PATH}/aviary/config
  CONFIG_FILE_URL="https://raw.githubusercontent.com/P5vc/ServerConfigurations/master/config"

  # Hostname Warning:
  echo -e "\n\n${BLUE}Make sure to set the server hostname so that it matches\none of the valid options under the hosts directory.\nThis hostname must be unique (not used by any other server).\nYou may set the hostname by running:\n${CYAN}sudo hostnamectl set-hostname <hostname>\n\n${PURPLE}The current hostname is: $(hostname)${NO_COLOR}\n\n"

  # check for git dependency
  if ! /usr/bin/which git > /dev/null; then
    apt-get update
    apt-get install git -y
  fi

  if [[ -z "$INVENTORY_GIT_URL" ]]; then
    echo "Installing with no inventory git url; set later in $CONFIG_FILE"
  fi

  if [[ -e /var/lib/aviary ]]; then 
    echo "Found existing installation at $INSTALL_PATH; exiting"
    exit 1
  fi

  echo Installing to ${INSTALL_PATH}...
  mkdir -p ${INSTALL_PATH}/aviary
  git clone $GIT_URL ${INSTALL_PATH}/aviary
  ln -sf /var/lib/aviary/av /usr/bin/av
  mkdir -p ${INSTALL_PATH}/aviary/inventory

  curl $CONFIG_FILE_URL -o ${INSTALL_PATH}/aviary/config

  echo Adding entry to /etc/crontab...
  echo "$(cat /etc/crontab | grep -v $AV_PATH)" > /etc/crontab
  echo "$(( RANDOM % 60 )) $(( RANDOM % 60 )) * * * root $AV_PATH directive >> /var/log/aviary-directive.log 2>&1" >> /etc/crontab
  echo "$(( RANDOM % 60 )) $(( RANDOM % 60 )) * * * root $AV_PATH apply >> /var/log/aviary.log 2>&1" >> /etc/crontab

  echo Done
}

run  # Wrap in function to ensure entire script is downloaded.
